{
  "code": 1,
  "subdomains": {
    "elasticsearch": {
      "code": 1,
      "errors": {
        "wrong_elasticsearch_version": {
          "code": 1,
          "message": "Your elasticsearch version is %s; Only elasticsearch version 7 is currently supported.",
          "class": "InternalError"
        },
        "unknown_scroll_identifier": {
          "code": 2,
          "message": "Non-existing or expired scroll identifier.",
          "class": "NotFoundError"
        },
        "wrong_get_action": {
          "code": 3,
          "message": "The action _search can't be done with a GET.",
          "class": "BadRequestError"
        },
        "index_or_collection_does_not_exist": {
          "code": 5,
          "message": "Index '%s' and/or collection '%s' don't exist.",
          "class": "PreconditionError"
        },
        "document_already_exists": {
          "code": 6,
          "message": "Document with id \"%s\" already exists.",
          "class": "BadRequestError"
        },
        "document_not_found": {
          "code": 7,
          "message": "Document with id \"%s\" not found.",
          "class": "NotFoundError"
        },
        "empty_query": {
          "code": 8,
          "message": "Query cannot be empty.",
          "class": "BadRequestError"
        },
        "document_id_cannot_be_null": {
          "code": 9,
          "message": "null is not a valid document ID.",
          "class": "BadRequestError"
        },
        "index_does_not_exist": {
          "code": 10,
          "message": "Index '%s' does not exist.",
          "class": "PreconditionError"
        },
        "missing_or_invalid_import_attribute": {
          "code": 11,
          "message": "import must specify a body attribute 'bulkData' of type Object.",
          "class": "BadRequestError"
        },
        "missing_collection_argument": {
          "code": 12,
          "message": "Missing collection argument at body[%s].",
          "class": "BadRequestError"
        },
        "missing_index_argument": {
          "code": 13,
          "message": "Missing index argument at body[%s].",
          "class": "BadRequestError"
        },
        "index_protected": {
          "code": 14,
          "message": "Index '%s' is protected, please use appropriated routes instead.",
          "class": "BadRequestError"
        },
        "error_on_index_refresh": {
          "code": 15,
          "message": "Error refreshing index %s:\n%s.",
          "class": "InternalError"
        },
        "limit_documents_reached": {
          "code": 16,
          "message": "Number of documents exceeds the server configured value (%s).",
          "class": "SizeLimitError"
        },
        "index_reserved": {
          "code": 17,
          "message": "Indexes starting with a '%' are reserved for internal use. Cannot process index %s.",
          "class": "BadRequestError",
          "deprecated": true
        },
        "create_action_does_not_support_routing": {
          "code": 18,
          "message": "Kuzzle does not support '_routing' in create action.",
          "class": "BadRequestError"
        },
        "wrong_refresh_parameter": {
          "code": 19,
          "message": "Refresh parameter only supports the value 'wait_for' or false.",
          "class": "BadRequestError"
        },
        "incorrect_mapping_property": {
          "code": 20,
          "message": "Incorrect mapping property \"mapping.%s\".%s",
          "class": "BadRequestError"
        },
        "too_many_operations": {
          "code": 21,
          "message": "\"%s\" threads buffer exceeded. Too many operations received at once.",
          "class": "ExternalServiceError"
        },
        "invalid_change_from_nested": {
          "code": 22,
          "message": "Can not change mapping for field \"%s\" from nested to another type.",
          "class": "BadRequestError"
        },
        "invalid_change_to_nested": {
          "code": 23,
          "message": "Can not change mapping for field \"%s\" from object to another type.",
          "class": "BadRequestError"
        },
        "invalid_change_to_scalar": {
          "code": 24,
          "message": "Can not change mapping for field \"%s\" from object to a scalar type.",
          "class": "BadRequestError"
        },
        "duplicate_field_name": {
          "code": 25,
          "message": "Can not set mapping for field \"%s\" on collection \"%s\" because the field name is already used in another collection with a different type.",
          "class": "BadRequestError"
        },
        "invalid_type_change": {
          "code": 26,
          "message": "Can not change type of field \"%s\" from \"%s\" to \"%s\".",
          "class": "BadRequestError"
        },
        "unsupported_parameter_for_field": {
          "code": 27,
          "message": "Parameter \"%s\" is not supported for field \"%s\".",
          "class": "BadRequestError"
        },
        "type_does_not_exist": {
          "code": 28,
          "message": "Can not set mapping for field \"%s\" because type \"%s\" does not exist",
          "class": "BadRequestError"
        },
        "fail_to_parse_field": {
          "code": 29,
          "message": "Failed to validate value of field \"%s\". Are you trying to insert nested value in a non-nested field ?",
          "class": "BadRequestError"
        },
        "wrong_mapping_property": {
          "code": 30,
          "message": "Mapping for field \"%s\" must be an object with a property \"type\".",
          "class": "BadRequestError"
        },
        "too_many_changes": {
          "code": 31,
          "message": "Unable to modify document \"%s\": cluster sync failed (too many simultaneous changes applied)",
          "class": "ExternalServiceError"
        },
        "elasticsearch_service_not_connected":{
          "code": 32,
          "message": "Elasticsearch service is not connected.",
          "class": "ExternalServiceError"
        },
        "unexpected_bad_request_error": {
          "code": 33,
          "message": "%s",
          "class": "BadRequestError"
        },
        "unexpected_not_found_error": {
          "code": 34,
          "message": "%s",
          "class": "NotFoundError"
        },
        "unexpected_conflict_error": {
          "code": 35,
          "message": "%s",
          "class": "ExternalServiceError"
        },
        "unexpected_error": {
          "code": 36,
          "message": "%s",
          "class": "ExternalServiceError"
        },
        "no_mapping_found": {
          "code": 37,
          "message": "No mapping found for index \"%s\".",
          "class": "NotFoundError"
        },
        "index_or_collection_not_found": {
          "code": 38,
          "message": "%s index \"%s\" or collection \"%s\" does not exist, please create it first.",
          "class": "NotFoundError"
        },
        "cannot_parse_mapping": {
          "code": 39,
          "message": "Cannot parse mapping property \"%s\": %s",
          "class": "BadRequestError"
        },
        "index_already_exists": {
          "code": 40,
          "message": "Index %s already exists.%s",
          "class": "BadRequestError"
        },
        "forbidden_character": {
          "code": 41,
          "message": "Forbidden character \"%s\" in index or collection name",
          "class": "BadRequestError"
        }
      }
    },
    "internal_engine": {
      "code": 2,
      "errors": {
        "lock_wait_timeout": {
          "code": 1,
          "message": "Internal engine bootstrap - lock wait timeout exceeded.",
          "class": "InternalError"
        },
        "plugin_bootstrap_lock_wait_timeout": {
          "code": 2,
          "message": "Plugin %s bootstrap - lock wait timeout exceeded.",
          "class": "InternalError"
        },
        "no_jwt_secret_available": {
          "code": 3,
          "message": "Potential race condition: no JWT secret is available in configuration or DB.",
          "class": "InternalError"
        }
      }
    },
    "redis": {
      "code": 3,
      "errors": {
        "redis_service_not_connected": {
          "code": 1,
          "message": "Redis service is not connected.",
          "class": "ServiceUnavailableError"
        }
      }
    },
    "common": {
      "code": 4,
      "errors": {
        "service_initialization_timeout": {
          "code": 1,
          "message": "[FATAL] Service \"%s\" failed to initialize within %sms.",
          "class": "InternalError"
        }
      }
    }
  }
}
