{
  "code": 0,
  "subdomains": {
    "fatal": {
      "code": 0,
      "errors": {
        "unexpected_error": {
          "code": 1,
          "message": "Unknown error: %s.",
          "class": "InternalError"
        },
        "service_unavailable": {
          "code": 2,
          "message": "Service unavailable: %s.",
          "class": "ServiceUnavailableError"
        },
        "service_timeout": {
          "code": 3,
          "message": "[FATAL] Service \"%s\": initialization timeout",
          "class": "InternalError"
        },
      }
    },
    "hotelclerk" : {
      "code": 2,
      "errors": {
        "room_id_not_exists": {
          "code": 1,
          "message": "The room Id \"%s\" does not exist.",
          "class": "NotFoundError"
        },
        "subscription_not_found": {
          "code": 2,
          "message": "No subscription found on index %s and collection %s.",
          "class": "NotFoundError"
        },
        "rooms_attribute_type": {
          "code": 3,
          "message": "The rooms attribute must be an array.",
          "class": "BadRequestError"
        },
        "incorrect_state_value": {
          "code": 4,
          "message": "Incorrect value for the 'state' parameter. Expected: all, done or pending. Got: %s.",
          "class": "BadRequestError"
        },
        "incorrect_scope_value": {
          "code": 5,
          "message": "Incorrect value for the 'scope' parameter. Expected: all, done or pending. Got: %s.",
          "class": "BadRequestError"
        },
        "incorrect_users_value": {
          "code": 6,
          "message": "Incorrect value for the 'users' parameter. Expected: all, done or pending. Got: %s.",
          "class": "BadRequestError"
        },
        "missing_subscription_parameter": {
          "code": 7,
          "message": "Cannot subscribe without an index and a collection.",
          "class": "BadRequestError"
        },
        "limit_minterms_reached": {
          "code": 8,
          "message": "Unable to subscribe: maximum number of minterms exceeded (max %s, received %s).",
          "class": "SizeLimitError"
        },
        "limit_unique_rooms_reached": {
          "code": 9,
          "message": "Unable to subscribe: maximum number of unique rooms reached.",
          "class": "SizeLimitError"
        },
        "cant_unsubscribe_unknown_user": {
          "code": 10,
          "message": "Unsubscribe error: no subscription found for that user.",
          "class": "NotFoundError"
        },
        "cant_unsubscribe_user_not_subscribed": {
          "code": 11,
          "message": "Unsubscribe error: not subscribed to %s.",
          "class": "NotFoundError"
        },
        "cant_unsubscribe_unknown_room": {
          "code": 12,
          "message": "Unsubscribe error: room %s not found.",
          "class": "InternalError"
        }
      }
    },
    "janitor": {
      "code": 3,
      "errors": {
        "import_data" : {
          "code": 1,
          "message" : "Some data was not imported for %s/%s (%s/%s).",
          "class": "PartialError"
        },
        "dump_already_generated": {
          "code": 2,
          "message": "A dump is already being generated. Skipping.",
          "class": "PreconditionError"
        },
        "reading_log_directory": {
          "code": 3,
          "message": "Cannot read log directory '%s' : %s.",
          "class": "InternalError"
        }
      }
    },
    "vault": {
      "code": 4,
      "errors": {
        "decrypt_secrets": {
          "code": 1,
          "message": "Cannot decrypt secrets: %s.",
          "class": "InternalError"
        },
        "vault_key_not_found": {
          "code": 2,
          "message": "Cannot find vault key. Aborting.",
          "class": "NotFoundError"
        }
      }
    },
    "statistics": {
      "code": 7,
      "errors": {
        "invalid_time_value": {
          "code": 1,
          "message": "Invalid time value",
          "class": "BadRequestError"
        }
      }
    },
    "sandbox": {
      "code": 8,
      "errors": {
        "process_already_running": {
          "code": 1,
          "message": "A process is already running for this sandbox",
          "class": "InternalError"
        },
        "timeout": {
          "code": 2,
          "message": "Timeout. The sandbox did not respond within %sms.",
          "class": "GatewayTimeoutError"
        }
      }
    },
    "configuration": {
      "code": 9,
      "errors": {
        "invalid_limits_configuration_format": {
          "code": 1,
          "message": "Invalid config.limits configuration format: please check your Kuzzle configuration files",
          "class": "InternalError"
        },
        "value_out_of_range": {
          "code": 2,
          "message": "Invalid configuration: value set for \"%s\" limit is outside the allowed range",
          "class": "InternalError"
        },
        "concurrentRequests_superior_to_requestsBufferSize": {
          "code": 3,
          "message": "Invalid configuration: the concurrentRequests limit configuration must be strictly inferior to requestsBufferSize",
          "class": "InternalError"
        },
        "requestsBufferWarningThreshold_out_of_range": {
          "code": 4,
          "message": "Invalid configuration: limits.requestsBufferWarningThreshold should be comprised between limits.concurrentRequests and limits.requestsBufferSize",
          "class": "InternalError"
        }
      }
    }
  }
}
