{
  "code": 3,
  "subdomains": {
    "http": {
      "code": 1,
      "errors": {
        "request_too_large": {
          "description": "The size of the request exceeds the server configured limit",
          "code": 1,
          "message": "Maximum HTTP request size exceeded.",
          "class": "SizeLimitError"
        },
        "unexpected_error": {
          "description": "Caught an unexpected HTTP parsing error",
          "code": 2,
          "message": "Caught an unexpected HTTP error: %s",
          "class": "BadRequestError"
        },
        "too_many_encodings": {
          "description": "The number of encodings exceeds the server configured limit",
          "code": 3,
          "message": "Too many encodings.",
          "class": "BadRequestError"
        },
        "unsupported_compression": {
          "description": "The request has been compressed using an unsupported compression algorithm",
          "code": 4,
          "message": "Unsupported compression algorithm \"%s\".",
          "class": "BadRequestError"
        },
        "compression_disabled": {
          "description": "The server has been configured to refuse compressed requests",
          "code": 5,
          "message": "Compression support is disabled.",
          "class": "BadRequestError"
        },
        "unsupported_verb": {
          "description": "An HTTP request has been submitted using an unsupported verb",
          "code": 6,
          "message": "Unsupported HTTP verb \"%s\".",
          "class": "BadRequestError"
        },
        "url_not_found": {
          "description": "API URL not found",
          "code": 7,
          "message": "API URL not found: %s.",
          "class": "NotFoundError"
        },
        "unsupported_content": {
          "description": "The content described in the content-type header is not supported",
          "code": 8,
          "message": "Invalid request content-type. Expected \"application/json\", got: \"%s\".",
          "class": "BadRequestError"
        },
        "unsupported_charset": {
          "description": "Unsupported content charset",
          "code": 9,
          "message": "Unsupported request charset. Expected \"utf-8\", got: \"%s\".",
          "class": "BadRequestError"
        },
        "duplicate_url": {
          "description": "Triggered when an attempt is made to register a duplicate URL in the HTTP router",
          "code": 10,
          "message": "Unable to attach URL %s: this path already exists.",
          "class": "InternalError"
        },
        "volatile_parse_failed": {
          "description": "The x-kuzzle-volatile header received is not in JSON format",
          "code": 11,
          "message": "Unable to convert the \"x-kuzzle-volatile\" HTTP header to JSON: %s",
          "class": "BadRequestError"
        },
        "body_parse_failed": {
          "description": "The request body is not in JSON format",
          "code": 12,
          "message": "Unable to convert the HTTP body to JSON: %s",
          "class": "BadRequestError"
        },
        "file_too_large": {
          "description": "The submitted file exceeds the server configured limit",
          "code": 13,
          "message": "Maximum HTTP file size exceeded",
          "class": "SizeLimitError"
        }
      }
    },
    "mqtt": {
      "code": 2,
      "errors": {
        "unexpected_error": {
          "description": "Caught an unexpected MQTT error",
          "code": 1,
          "message": "Caught an unexpected MQTT error: %s",
          "class": "BadRequestError"
        }
      }
    },
    "websocket": {
      "code": 3,
      "errors": {
        "unexpected_error": {
          "description": "Caught an unexpected WebSocket error",
          "code": 1,
          "message": "Caught an unexpected WebSocket error: %s",
          "class": "BadRequestError"
        }
      }
    },
    "entrypoint": {
      "code": 4,
      "errors": {
        "unexpected_event": {
          "description": "Received an erroneous network event",
          "code": 1,
          "message": "Unexpected event received: %s.",
          "class": "InternalError"
        },
        "invalid_port": {
          "description": "Invalid network port",
          "code": 2,
          "message": "Invalid network port number: %s.",
          "class": "InternalError"
        },
        "shutting_down": {
          "description": "Request rejected because this instance is shutting down",
          "code": 3,
          "message": "Rejected: instance is shutting down",
          "class": "ServiceUnavailableError"
        }
      }
    }
  }
}
